#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION "2020.3.15f2"
#define UNITY_VERSION_DIGITS "2020.3.15"
#define UNITY_VERSION_SUFFIX "f2"
#define UNITY_VERSION_VER 2020
#define UNITY_VERSION_MAJ 3
#define UNITY_VERSION_MIN 15
#define UNITY_IS_BETA 0
